In [29]:
import pandas as pd
import numpy as np
from sklearn import svm
from sklearn.datasets import load_iris
iris = load_iris()

In [30]:
df = pd.DataFrame(iris.data, columns = iris.feature_names)
df['flower'] = iris.target
df['flower'] = df['flower'].apply(lambda x : iris.target_names[x])
df

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),flower
0,5.1,3.5,1.4,0.2,setosa
1,4.9,3.0,1.4,0.2,setosa
2,4.7,3.2,1.3,0.2,setosa
3,4.6,3.1,1.5,0.2,setosa
4,5.0,3.6,1.4,0.2,setosa
...,...,...,...,...,...
145,6.7,3.0,5.2,2.3,virginica
146,6.3,2.5,5.0,1.9,virginica
147,6.5,3.0,5.2,2.0,virginica
148,6.2,3.4,5.4,2.3,virginica
149,5.9,3.0,5.1,1.8,virginica

In [31]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(iris.data , iris.target , test_size = 0.25)

In [32]:
model = svm.SVC(kernel = 'rbf' , C = 30 , gamma = 'auto')
model.fit(X_train, y_train)
model.score(X_test , y_test)

1.0

In [33]:
from sklearn.model_selection import cross_val_score

In [34]:
x = cross_val_score(svm.SVC(kernel = 'linear' , C = 10 , gamma = 'auto') , iris.data , iris.target , cv = 5).mean()
x

0.9733333333333334

In [35]:
y = cross_val_score(svm.SVC(kernel = 'rbf' , C = 10 , gamma = 'auto') , iris.data , iris.target , cv = 5).mean()
y

0.9800000000000001

In [36]:
z = cross_val_score(svm.SVC(kernel = 'rbf' , C = 20 , gamma = 'auto') , iris.data , iris.target , cv = 5).mean()
z

0.9666666666666668

In [52]:
kernels = ['rbf', 'linear']
C = [1,10,20,30,50]
avg_scores = {}
for kval in kernels:
    for cval in C:
        cv_scores = cross_val_score(svm.SVC(kernel=kval,C=cval,gamma='auto'),iris.data, iris.target, cv=5)
        avg_scores[kval + '_' + str(cval)] = np.average(cv_scores)

avg_scores

{'rbf_1': 0.9800000000000001,
 'rbf_10': 0.9800000000000001,
 'rbf_20': 0.9666666666666668,
 'rbf_30': 0.96,
 'rbf_50': 0.96,
 'linear_1': 0.9800000000000001,
 'linear_10': 0.9733333333333334,
 'linear_20': 0.9666666666666666,
 'linear_30': 0.96,
 'linear_50': 0.9666666666666666}

In [53]:
from sklearn.model_selection import GridSearchCV
clf = GridSearchCV(svm.SVC(gamma='auto'), {
    'C': [1,10,20,30,50],
    'kernel': ['rbf','linear']
}, cv=5, return_train_score=False)
clf.fit(iris.data, iris.target)
clf.cv_results_

{'mean_fit_time': array([0.00040178, 0.00071926, 0.00040097, 0.00030103, 0.00010109,
        0.00090866, 0.0004035 , 0.        , 0.00060768, 0.00060024]),
 'std_fit_time': array([0.00049208, 0.00041512, 0.00049109, 0.00040115, 0.00020218,
        0.00046746, 0.0004942 , 0.        , 0.0004963 , 0.0004901 ]),
 'mean_score_time': array([0.00070181, 0.00040121, 0.00070343, 0.00040817, 0.00087638,
        0.0002243 , 0.        , 0.00110946, 0.00048232, 0.00044045]),
 'std_score_time': array([0.00060152, 0.00049138, 0.00060219, 0.00050004, 0.00044627,
        0.00044861, 0.        , 0.00013833, 0.00060451, 0.00054304]),
 'param_C': masked_array(data=[1, 1, 10, 10, 20, 20, 30, 30, 50, 50],
              mask=[False, False, False, False, False, False, False, False,
                    False, False],
        fill_value='?',
             dtype=object),
 'param_kernel': masked_array(data=['rbf', 'linear', 'rbf', 'linear', 'rbf', 'linear',
                    'rbf', 'linear', 'rbf', 'linear'],
              mask=[False, False, False, False, False, False, False, False,
                    False, False],
        fill_value='?',
             dtype=object),
 'params': [{'C': 1, 'kernel': 'rbf'},
  {'C': 1, 'kernel': 'linear'},
  {'C': 10, 'kernel': 'rbf'},
  {'C': 10, 'kernel': 'linear'},
  {'C': 20, 'kernel': 'rbf'},
  {'C': 20, 'kernel': 'linear'},
  {'C': 30, 'kernel': 'rbf'},
  {'C': 30, 'kernel': 'linear'},
  {'C': 50, 'kernel': 'rbf'},
  {'C': 50, 'kernel': 'linear'}],
 'split0_test_score': array([0.96666667, 0.96666667, 0.96666667, 1.        , 0.96666667,
        1.        , 0.96666667, 1.        , 1.        , 1.        ]),
 'split1_test_score': array([1.        , 1.        , 1.        , 1.        , 1.        ,
        1.        , 1.        , 1.        , 0.96666667, 1.        ]),
 'split2_test_score': array([0.96666667, 0.96666667, 0.96666667, 0.9       , 0.9       ,
        0.9       , 0.9       , 0.9       , 0.9       , 0.9       ]),
 'split3_test_score': array([0.96666667, 0.96666667, 0.96666667, 0.96666667, 0.96666667,
        0.93333333, 0.93333333, 0.9       , 0.93333333, 0.93333333]),
 'split4_test_score': array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]),
 'mean_test_score': array([0.98      , 0.98      , 0.98      , 0.97333333, 0.96666667,
        0.96666667, 0.96      , 0.96      , 0.96      , 0.96666667]),
 'std_test_score': array([0.01632993, 0.01632993, 0.01632993, 0.03887301, 0.03651484,
        0.0421637 , 0.03887301, 0.04898979, 0.03887301, 0.0421637 ]),
 'rank_test_score': array([1, 1, 1, 4, 5, 6, 8, 8, 8, 6])}

In [54]:
df = pd.DataFrame(clf.cv_results_)
df

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_C,param_kernel,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.000402,0.000492,0.000702,0.000602,1,rbf,"{'C': 1, 'kernel': 'rbf'}",0.966667,1.000000,0.966667,0.966667,1.0,0.980000,0.016330,1
1,0.000719,0.000415,0.000401,0.000491,1,linear,"{'C': 1, 'kernel': 'linear'}",0.966667,1.000000,0.966667,0.966667,1.0,0.980000,0.016330,1
2,0.000401,0.000491,0.000703,0.000602,10,rbf,"{'C': 10, 'kernel': 'rbf'}",0.966667,1.000000,0.966667,0.966667,1.0,0.980000,0.016330,1
3,0.000301,0.000401,0.000408,0.000500,10,linear,"{'C': 10, 'kernel': 'linear'}",1.000000,1.000000,0.900000,0.966667,1.0,0.973333,0.038873,4
4,0.000101,0.000202,0.000876,0.000446,20,rbf,"{'C': 20, 'kernel': 'rbf'}",0.966667,1.000000,0.900000,0.966667,1.0,0.966667,0.036515,5
5,0.000909,0.000467,0.000224,0.000449,20,linear,"{'C': 20, 'kernel': 'linear'}",1.000000,1.000000,0.900000,0.933333,1.0,0.966667,0.042164,6
6,0.000403,0.000494,0.000000,0.000000,30,rbf,"{'C': 30, 'kernel': 'rbf'}",0.966667,1.000000,0.900000,0.933333,1.0,0.960000,0.038873,8
7,0.000000,0.000000,0.001109,0.000138,30,linear,"{'C': 30, 'kernel': 'linear'}",1.000000,1.000000,0.900000,0.900000,1.0,0.960000,0.048990,8
8,0.000608,0.000496,0.000482,0.000605,50,rbf,"{'C': 50, 'kernel': 'rbf'}",1.000000,0.966667,0.900000,0.933333,1.0,0.960000,0.038873,8
9,0.000600,0.000490,0.000440,0.000543,50,linear,"{'C': 50, 'kernel': 'linear'}",1.000000,1.000000,0.900000,0.933333,1.0,0.966667,0.042164,6

In [55]:
df[['param_C' , 'param_kernel' , 'mean_test_score' , 'rank_test_score']]

  param_C param_kernel  mean_test_score  rank_test_score
0       1          rbf         0.980000                1
1       1       linear         0.980000                1
2      10          rbf         0.980000                1
3      10       linear         0.973333                4
4      20          rbf         0.966667                5
5      20       linear         0.966667                6
6      30          rbf         0.960000                8
7      30       linear         0.960000                8
8      50          rbf         0.960000                8
9      50       linear         0.966667                6

In [56]:
dir(clf)

['__abstractmethods__',
 '__annotations__',
 '__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__setstate__',
 '__sizeof__',
 '__sklearn_clone__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_abc_impl',
 '_build_request_for_signature',
 '_check_feature_names',
 '_check_n_features',
 '_check_refit_for_multimetric',
 '_doc_link_module',
 '_doc_link_template',
 '_doc_link_url_param_generator',
 '_estimator_type',
 '_format_results',
 '_get_default_requests',
 '_get_doc_link',
 '_get_metadata_request',
 '_get_param_names',
 '_get_routed_params_for_fit',
 '_get_scorers',
 '_get_tags',
 '_more_tags',
 '_parameter_constraints',
 '_repr_html_',
 '_repr_html_inner',
 '_repr_mimebundle_',
 '_required_parameters',
 '_run_search',
 '_select_best_index',
 '_validate_data',
 '_validate_params',
 'best_estimator_',
 'best_index_',
 'best_params_',
 'best_score_',
 'classes_',
 'cv',
 'cv_results_',
 'decision_function',
 'error_score',
 'estimator',
 'fit',
 'get_metadata_routing',
 'get_params',
 'inverse_transform',
 'multimetric_',
 'n_features_in_',
 'n_jobs',
 'n_splits_',
 'param_grid',
 'pre_dispatch',
 'predict',
 'predict_log_proba',
 'predict_proba',
 'refit',
 'refit_time_',
 'return_train_score',
 'score',
 'score_samples',
 'scorer_',
 'scoring',
 'set_params',
 'transform',
 'verbose']

In [58]:
from sklearn.model_selection import RandomizedSearchCV
rs = RandomizedSearchCV(svm.SVC(gamma='auto'), {
        'C': [1,10,20],
        'kernel': ['rbf','linear']
    }, 
    cv=5, 
    return_train_score=False, 
    n_iter=2
)
rs.fit(iris.data, iris.target)
pd.DataFrame(rs.cv_results_)[['param_C','param_kernel','mean_test_score']]

  param_C param_kernel  mean_test_score
0      10       linear         0.973333
1      20          rbf         0.966667

In [59]:
from sklearn import svm
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression

model_params = {
    'svm': {
        'model': svm.SVC(gamma='auto'),
        'params' : {
            'C': [1,10,20],
            'kernel': ['rbf','linear']
        }  
    },
    'random_forest': {
        'model': RandomForestClassifier(),
        'params' : {
            'n_estimators': [1,5,10]
        }
    },
    'logistic_regression' : {
        'model': LogisticRegression(solver='liblinear',multi_class='auto'),
        'params': {
            'C': [1,5,10]
        }
    }
}

In [60]:
scores = []

for model_name, mp in model_params.items():
    clf =  GridSearchCV(mp['model'], mp['params'], cv=5, return_train_score=False)
    clf.fit(iris.data, iris.target)
    scores.append({
        'model': model_name,
        'best_score': clf.best_score_,
        'best_params': clf.best_params_
    })
    
df = pd.DataFrame(scores,columns=['model','best_score','best_params'])
df

                 model  best_score                best_params
0                  svm    0.980000  {'C': 1, 'kernel': 'rbf'}
1        random_forest    0.973333        {'n_estimators': 5}
2  logistic_regression    0.966667                   {'C': 5}